BEGIN;

SELECT plan(8);

-- The seed contract intentionally fixes user identities and observable
-- collaboration data. Aggregate UUIDs generated by command functions are not
-- fixtures and may change after each database reset.

SELECT results_eq(
    $$
        SELECT user_id, username, display_name, status
        FROM public.current_profiles
        WHERE user_id IN (
            '10000000-0000-4000-8000-000000000001'::UUID,
            '10000000-0000-4000-8000-000000000002'::UUID,
            '10000000-0000-4000-8000-000000000003'::UUID
        )
        ORDER BY user_id
    $$,
    $$
        VALUES
            (
                '10000000-0000-4000-8000-000000000001'::UUID,
                'workspace-owner'::TEXT,
                'Workspace Owner'::TEXT,
                'active'::TEXT
            ),
            (
                '10000000-0000-4000-8000-000000000002'::UUID,
                'workspace-member'::TEXT,
                'Workspace Member'::TEXT,
                'active'::TEXT
            ),
            (
                '10000000-0000-4000-8000-000000000003'::UUID,
                'workspace-outsider'::TEXT,
                'Workspace Outsider'::TEXT,
                'active'::TEXT
            )
    $$,
    'the three stable identities have deterministic active profiles'
);

SELECT results_eq(
    $$
        SELECT name, slug, description, status, created_by
        FROM public.current_workspaces
        WHERE slug = 'omoikane-development'
    $$,
    $$
        VALUES (
            'Omoikane Development'::TEXT,
            'omoikane-development'::TEXT,
            'Local workspace populated by supabase/seed.sql'::TEXT,
            'active'::TEXT,
            '10000000-0000-4000-8000-000000000001'::UUID
        )
    $$,
    'the development workspace has deterministic current content'
);

SELECT results_eq(
    $$
        SELECT
            memberships.user_id,
            memberships.membership_role,
            memberships.membership_status
        FROM public.current_workspace_memberships AS memberships
        INNER JOIN public.current_workspaces AS workspaces
            ON workspaces.workspace_id = memberships.workspace_id
        WHERE workspaces.slug = 'omoikane-development'
        ORDER BY memberships.user_id
    $$,
    $$
        VALUES
            (
                '10000000-0000-4000-8000-000000000001'::UUID,
                'owner'::TEXT,
                'active'::TEXT
            ),
            (
                '10000000-0000-4000-8000-000000000002'::UUID,
                'member'::TEXT,
                'active'::TEXT
            )
    $$,
    'the workspace has the expected owner and member'
);

SELECT is(
    (
        SELECT count(*)
        FROM public.current_workspace_memberships
        WHERE user_id =
            '10000000-0000-4000-8000-000000000003'::UUID
    ),
    0::BIGINT,
    'the outsider has no workspace membership'
);

SELECT results_eq(
    $$
        SELECT
            channels.name,
            channels.slug,
            channels.description,
            channels.channel_status
        FROM public.current_channels AS channels
        INNER JOIN public.current_workspaces AS workspaces
            ON workspaces.workspace_id = channels.workspace_id
        WHERE workspaces.slug = 'omoikane-development'
        ORDER BY channels.slug
    $$,
    $$
        VALUES
            (
                'Engineering'::TEXT,
                'engineering'::TEXT,
                'Technical discussion for local development'::TEXT,
                'active'::TEXT
            ),
            (
                'General'::TEXT,
                'general'::TEXT,
                'General conversation for local development'::TEXT,
                'active'::TEXT
            )
    $$,
    'the workspace has the expected active channels'
);

SELECT is(
    (
        SELECT count(*)
        FROM public.current_messages AS messages
        INNER JOIN public.current_workspaces AS workspaces
            ON workspaces.workspace_id = messages.workspace_id
        WHERE workspaces.slug = 'omoikane-development'
          AND messages.message_status = 'active'
    ),
    5::BIGINT,
    'the workspace has five active seed messages'
);

SELECT results_eq(
    $$
        SELECT
            channels.slug,
            messages.content,
            messages.author_user_id
        FROM public.current_messages AS messages
        INNER JOIN public.current_channels AS channels
            ON channels.channel_id = messages.channel_id
        INNER JOIN public.current_workspaces AS workspaces
            ON workspaces.workspace_id = messages.workspace_id
        WHERE workspaces.slug = 'omoikane-development'
          AND messages.message_status = 'active'
        ORDER BY channels.slug, messages.content
    $$,
    $$
        VALUES
            (
                'engineering'::TEXT,
                'The Angular, Effect, and Supabase foundations are connected.'::TEXT,
                '10000000-0000-4000-8000-000000000001'::UUID
            ),
            (
                'engineering'::TEXT,
                'The seeded workspace is ready for local collaboration.'::TEXT,
                '10000000-0000-4000-8000-000000000002'::UUID
            ),
            (
                'general'::TEXT,
                'Hello from the seeded workspace member.'::TEXT,
                '10000000-0000-4000-8000-000000000002'::UUID
            ),
            (
                'general'::TEXT,
                'This message was created by the workspace owner.'::TEXT,
                '10000000-0000-4000-8000-000000000001'::UUID
            ),
            (
                'general'::TEXT,
                'Welcome to the local Omoikane development workspace.'::TEXT,
                '10000000-0000-4000-8000-000000000001'::UUID
            )
    $$,
    'seed message content and channel placement are deterministic'
);

SELECT results_eq(
    $$
        SELECT messages.author_user_id, count(*)
        FROM public.current_messages AS messages
        INNER JOIN public.current_workspaces AS workspaces
            ON workspaces.workspace_id = messages.workspace_id
        WHERE workspaces.slug = 'omoikane-development'
          AND messages.message_status = 'active'
        GROUP BY messages.author_user_id
        ORDER BY messages.author_user_id
    $$,
    $$
        VALUES
            (
                '10000000-0000-4000-8000-000000000001'::UUID,
                3::BIGINT
            ),
            (
                '10000000-0000-4000-8000-000000000002'::UUID,
                2::BIGINT
            )
    $$,
    'seed message authorship is deterministic'
);

SELECT * FROM finish();

ROLLBACK;
