allowBuilds:
  '@parcel/watcher': true
  '@scarf/scarf': false
  esbuild: true
  less: true
  lmdb: true
  msgpackr-extract: true
  nx: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@angular/cdk@22.0.6'
