import { execSync } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

const outputPath = resolve(
  'libs/shared/database/src/generated/database.types.ts'
);

mkdirSync(dirname(outputPath), { recursive: true });

const generatedTypes = execSync(
  'pnpm exec supabase gen types typescript --local --schema public',
  {
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'inherit'],
    windowsHide: true,
  }
);

const header = `/**
 * AUTO-GENERATED FILE.
 *
 * Generated from the local Supabase database schema.
 * Do not edit this file manually.
 */

`;

writeFileSync(outputPath, header + generatedTypes, 'utf8');

console.log(`Generated database types: ${outputPath}`);
