import { execSync } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

const outputPath = resolve(
  'libs/shared/database/src/generated/database.types.ts'
);

mkdirSync(dirname(outputPath), { recursive: true });

const generatedTypes = execSync(
  'pnpm exec supabase gen types typescript --local --schema public',
  {
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'inherit'],
    windowsHide: true,
  }
);

// Package-manager shims may write status messages to stdout before forwarding
// the Supabase CLI output. Keep only the generated TypeScript contract and fail
// explicitly if the CLI's stable opening declaration is absent.
const generatedContractMarker = 'export type Json =';
const generatedContractStart = generatedTypes.indexOf(generatedContractMarker);

if (generatedContractStart < 0) {
  throw new Error(
    `Supabase type output did not contain ${JSON.stringify(generatedContractMarker)}.`
  );
}

const generatedContract = generatedTypes.slice(generatedContractStart);

const header = `/**
 * AUTO-GENERATED FILE.
 *
 * Generated from the local Supabase database schema.
 * Do not edit this file manually.
 */

`;

// Supabase CLI output has varied in line endings and trailing blank lines
// across operating systems. Normalize only that whitespace boundary so the
// checked-in generated contract remains byte-identical locally and in CI.
const normalizedGeneratedTypes = generatedContract
  .replace(/\r\n?/gu, '\n')
  .trimEnd();

writeFileSync(outputPath, `${header}${normalizedGeneratedTypes}\n`, 'utf8');

console.log(`Generated database types: ${outputPath}`);
