import { execSync } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

const outputPath = resolve(
  'libs/shared/database/src/generated/database.types.ts'
);

mkdirSync(dirname(outputPath), { recursive: true });

const generatedTypes = execSync(
  'pnpm exec supabase gen types typescript --local --schema public',
  {
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'inherit'],
    windowsHide: true,
  }
);

const header = `/**
 * AUTO-GENERATED FILE.
 *
 * Generated from the local Supabase database schema.
 * Do not edit this file manually.
 */

`;

// Supabase CLI output has varied in line endings and trailing blank lines
// across operating systems. Normalize only that whitespace boundary so the
// checked-in generated contract remains byte-identical locally and in CI.
const normalizedGeneratedTypes = generatedTypes
  .replace(/\r\n?/gu, '\n')
  .trimEnd();

writeFileSync(outputPath, `${header}${normalizedGeneratedTypes}\n`, 'utf8');

console.log(`Generated database types: ${outputPath}`);
